# Ant
# Build your Java projects and run tests with Apache Ant.
# Add steps that save build artifacts and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  name: my-host

steps:
- script: pwd        
  displayName: Getting present working directory
- script: ant clean
  displayName: Ant clean process
- script: ant compile
  displayName: compiling code 
- script: ant jar
  displayName: building jar file
- script: |
    cd /home/azureuser/oe-core
    pwd
    echo "getting username"
    whoami
    echo "Job started running"
    java -jar /home/azureuser/work/3/s/dist/CommandsExecutionJob.jar
    echo "job has been completed"
  displayName: Executing JOb  
  